In [15]:
import torch
from torch import autograd
from torch import nn
from torch import optim
import torch.nn.functional as F

torch.manual_seed(1)

# 1. Introduction to Torch's tensor library

In [16]:
# creating tensors

V_data = [1., 2., 3.]
V = torch.Tensor(V_data)
print(V)

# create a matrix

M_data = [[1., 2., 3.], [4., 5., 6.]]
M = torch.Tensor(M_data)
print(M)

# create 3d tensor
T_data = [[[1., 2.], [3., 4.],
           [5., 6.], [7., 8.]]]
T = torch.Tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]])


In [17]:
tmp_tensor = torch.Tensor([[1, 2, 3, 4], [0, 0, 0, 0]])
print(tmp_tensor.shape)
tmp_tensor = torch.Tensor([[[1, 2, 3],
                            [0, 0, 0]]])
print(tmp_tensor.shape)

torch.Size([2, 4])
torch.Size([1, 2, 3])


In [18]:
print(V[0])
print(M[0])
print(T[0])

tensor(1.)
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [19]:
x = torch.randn(3, 4, 5)
print(x)

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])


In [20]:
# tensor operations
x = torch.tensor([1, 2, 3], dtype=torch.float32)
y = torch.tensor([4, 5, 6], dtype=torch.float32)
z = x + y
z

tensor([5., 7., 9.])

In [21]:
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1.shape)

x_2 = torch.randn(2, 6)
y_2 = torch.randn(2, 8)
z_2 = torch.cat([x_2, y_2], 1)
print(z_2.shape)

torch.Size([5, 5])
torch.Size([2, 14])


In [22]:
# reshaping tensor
x = torch.randn(2, 3, 4)
print(x.shape)
print(x.view(2, 12).shape)
print(x.view(2, -1).shape)

torch.Size([2, 3, 4])
torch.Size([2, 12])
torch.Size([2, 12])


# 2. Computation Graphs and Automatic Differentiation

In [23]:
# Variables wrap tensor objects
x = autograd.Variable(torch.Tensor([1., 2., 3.]), requires_grad=True)
print(x.data)

# also can do tensor operation
y = autograd.Variable(torch.Tensor([4., 5., 6.]), requires_grad=True)
z = x + y
print(z.data)

# but z knows something extra
print(z.grad_fn)

tensor([1., 2., 3.])
tensor([5., 7., 9.])


In [24]:
# Lets sum up all the entries in z
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [25]:
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [26]:
x = torch.randn((2, 2))
y = torch.randn((2, 2))
z = x + y

var_x = autograd.Variable(x, requires_grad=True)
var_y = autograd.Variable(y, requires_grad=True)
var_z = var_x + var_y
print(var_z.grad_fn)

var_z_data = var_z.data
new_var_z = autograd.Variable(var_z_data, requires_grad=True)

print(new_var_z.grad_fn)

None


# 3. Deep Learning Building Blocks: Affine maps, non-linearities and objectives

In [28]:
lin = nn.Linear(5, 3) # maps from R^5 to R^3, parameters A, b
data = autograd.Variable( torch.randn(2, 5) ) # data is 2x5.  A maps from 5 to 3... can we map "data" under A?
print(lin(data)) # yes

tensor([[ 0.4724,  0.2742,  0.9672],
        [-0.2771, -0.2918,  0.4074]], grad_fn=<AddmmBackward0>)


In [29]:
data = autograd.Variable(torch.randn(2, 2), requires_grad=True)
print(data)
print(F.relu(data))

tensor([[-1.4105, -0.3404],
        [-3.0121,  0.5710]], requires_grad=True)
tensor([[0.0000, 0.0000],
        [0.0000, 0.5710]], grad_fn=<ReluBackward0>)


In [31]:
# softmax
data = autograd.Variable(torch.randn(5), requires_grad=True)
print(data)
print(F.softmax(data, 0))
print(F.softmax(data, 0).sum())
print(F.log_softmax(data, 0))

tensor([ 0.4975,  0.3865, -1.5278,  0.3892, -0.7429], requires_grad=True)
tensor([0.3112, 0.2785, 0.0411, 0.2792, 0.0900], grad_fn=<SoftmaxBackward0>)
tensor(1., grad_fn=<SumBackward0>)
tensor([-1.1673, -1.2784, -3.1927, -1.2757, -2.4078],
       grad_fn=<LogSoftmaxBackward0>)


# 4. Optimization and Training

In [32]:
"""
there is no code in this section just reading
"""

'\nthere is no code in this section just reading\n'

# 5. Creating Network Components in Pytorch

In [33]:
data = [ ("me gusta comer en la cafeteria".split(), "SPANISH"),
         ("Give it to me".split(), "ENGLISH"),
         ("No creo que sea una buena idea".split(), "SPANISH"),
         ("No it is not a good idea to get lost at sea".split(), "ENGLISH") ]

test_data = [ ("Yo creo que si".split(), "SPANISH"),
              ("it is lost on me".split(), "ENGLISH")]

# word_to_ix maps each word in the vocab to a unique integer, which will be its
# index into the Bag of words vector
word_to_ix = {}
for sent, _ in data + test_data:
    for word in sent:
        if word not in word_to_ix:
            word_to_ix[word] = len(word_to_ix)

print(word_to_ix)
VOCAB_SIZE = len(word_to_ix)
NUM_LABELS = 2

{'me': 0, 'gusta': 1, 'comer': 2, 'en': 3, 'la': 4, 'cafeteria': 5, 'Give': 6, 'it': 7, 'to': 8, 'No': 9, 'creo': 10, 'que': 11, 'sea': 12, 'una': 13, 'buena': 14, 'idea': 15, 'is': 16, 'not': 17, 'a': 18, 'good': 19, 'get': 20, 'lost': 21, 'at': 22, 'Yo': 23, 'si': 24, 'on': 25}


In [ ]:
class BoWClassifier(nn.Module):
    pass