<a href="https://colab.research.google.com/github/deniandriancode/colab-notebooks/blob/main/Deep_Learning_for_NLP_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import autograd
from torch import nn
from torch import optim
import torch.nn.functional as F

torch.manual_seed(1)

# 1. Introduction to Torch's tensor library

In [2]:
# creating tensors

V_data = [1., 2., 3.]
V = torch.Tensor(V_data)
print(V)

# create a matrix

M_data = [[1., 2., 3.], [4., 5., 6.]]
M = torch.Tensor(M_data)
print(M)

# create 3d tensor
T_data = [[[1., 2.], [3., 4.],
           [5., 6.], [7., 8.]]]
T = torch.Tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]])


In [4]:
tmp_tensor = torch.Tensor([[1, 2, 3, 4], [0, 0, 0, 0]])
print(tmp_tensor.shape)
tmp_tensor = torch.Tensor([[[1, 2, 3],
                            [0, 0, 0]]])
print(tmp_tensor.shape)

torch.Size([2, 4])
torch.Size([1, 2, 3])


In [5]:
print(V[0])
print(M[0])
print(T[0])

tensor(1.)
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [6]:
x = torch.randn(3, 4, 5)
print(x)

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])


In [9]:
# tensor operations
x = torch.tensor([1, 2, 3], dtype=torch.float32)
y = torch.tensor([4, 5, 6], dtype=torch.float32)
z = x + y
z

tensor([5., 7., 9.])

In [13]:
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1.shape)

x_2 = torch.randn(2, 6)
y_2 = torch.randn(2, 8)
z_2 = torch.cat([x_2, y_2], 1)
print(z_2.shape)

torch.Size([5, 5])
torch.Size([2, 14])


In [14]:
# reshaping tensor
x = torch.randn(2, 3, 4)
print(x.shape)
print(x.view(2, 12).shape)
print(x.view(2, -1).shape)

torch.Size([2, 3, 4])
torch.Size([2, 12])
torch.Size([2, 12])


# 2. Computation Graphs and Automatic Differentiation